# Licensed under the MIT License
# https://github.com/craigahobbs/bare-script/blob/main/LICENSE


# Download javascript-build
JAVASCRIPT_BUILD_DIR ?= ../javascript-build
define WGET
ifeq '$$(wildcard $(notdir $(1)))' ''
$$(info Downloading $(notdir $(1)))
$$(shell [ -f $(JAVASCRIPT_BUILD_DIR)/$(notdir $(1)) ] && cp $(JAVASCRIPT_BUILD_DIR)/$(notdir $(1)) . || $(call WGET_CMD, $(1)))
endif
endef
WGET_CMD = if command -v wget >/dev/null 2>&1; then wget -q -c $(1); else curl -f -Os $(1); fi
$(eval $(call WGET, https://craigahobbs.github.io/javascript-build/Makefile.base))
$(eval $(call WGET, https://craigahobbs.github.io/javascript-build/jsdoc.json))
$(eval $(call WGET, https://craigahobbs.github.io/javascript-build/eslint.config.js))


# Include javascript-build
include Makefile.base


ESLINT_ARGS := $(ESLINT_ARGS) bin/ perf/


help:
	@echo "            [perf|sync|test-include]"


clean:
	rm -rf Makefile.base jsdoc.json eslint.config.js


.PHONY: sync
sync:
	cp SKILL.md ../bare-script-py/
	rsync -rv --delete --exclude=.git/ lib/include/ ../bare-script-py/src/bare_script/include/
	rsync -rv --delete --exclude=.git/ static/ ../bare-script-py/static/


# Generate the include library source module
_test _lint _cover _doc test-include-lint test-include-markdownup test-include-run perf: lib/includeSource.js
lib/includeSource.js: Makefile $(sort $(wildcard lib/include/*.bare)) | build/npm.build
	$(NODE_SHELL) node --input-type=module -e "$$INCLUDE_SOURCE_JS" $@ $(filter %.bare,$^)


# JavaScript to generate the include library source module
define INCLUDE_SOURCE_JS
import {barescriptParseScript} from './lib/runtime.js';
import {readFileSync, writeFileSync} from 'node:fs';
import {argv} from 'node:process';
import {gzipSync} from 'node:zlib';

// Command-line arguments
const [, outputPath, ...includePaths] = argv;

// Generate the include library source module
const parts = [`\
// Licensed under the MIT License
// https://github.com/craigahobbs/bare-script/blob/main/LICENSE

/**
 * @module lib/includeSource
 * @ignore
 */

// This file is generated by "make lib/includeSource.js" - do not edit


// Decode the map of include file name to gzip-compressed, base64-encoded include script model JSON
const includeSourceDecode = async (encodedIncludes) => Object.fromEntries(await Promise.all(
    Object.entries(encodedIncludes).map(async ([includeName, encoded]) => {
        // Base64-decode to bytes
        const binary = atob(encoded);
        const bytes = new Uint8Array(binary.length);
        for (let ixByte = 0; ixByte < binary.length; ixByte++) {
            bytes[ixByte] = binary.charCodeAt(ixByte);
        }

        // Inflate and UTF-8 decode - the Web streams APIs work in browsers and Node.js 18+ without a dependency
        const stream = new DecompressionStream('gzip');
        const writer = stream.writable.getWriter();
        writer.write(bytes);
        writer.close();
        const decoder = new TextDecoder();
        let text = '';
        for await (const chunk of stream.readable) {
            text += decoder.decode(chunk, {'stream': true});
        }
        return [includeName, text + decoder.decode()];
    })
));


// The map of system include file name to include script model JSON
export const systemIncludes = await includeSourceDecode({
`];
const includes = [];
for (const includePath of includePaths) {
    const includeName = includePath.slice(includePath.lastIndexOf('/') + 1, -'.bare'.length);
    const includeText = readFileSync(includePath, {'encoding': 'utf-8'});
    // Each include is embedded as its parser-compiled JSON script model ("scriptLines" omitted - it's unused
    // at runtime for system includes), gzip-compressed, base64-encoded, and chunked into 120-character string
    // lines, decoded at module load - the runtimes JSON-parse any system include starting with "{"
    const includeModel = barescriptParseScript(includeText, 1, `$${includeName}.bare`);
    delete includeModel.scriptLines;
    const modelEncoded = gzipSync(JSON.stringify(includeModel), {'level': 9}).toString('base64');
    const modelLinesText = modelEncoded.match(/.{1,120}/g).map((chunk) => `        '$${chunk}'`).join(',\n');
    includes.push(`    '$${includeName}.bare': [\n$${modelLinesText}\n    ].join('')`);
}
parts.push(`$${includes.join(',\n')}\n});\n`);
writeFileSync(outputPath, parts.join(''));
endef
export INCLUDE_SOURCE_JS


# The include-test sub-targets are independent so they run in parallel under "make -j"
.PHONY: test-include test-include-lint test-include-markdownup test-include-run
commit: test-include
test-include: test-include-lint test-include-markdownup test-include-run
test-include-lint test-include-markdownup test-include-run: build/npm.build
test-include-lint:
	$(NODE_SHELL) npx bare -x -m lib/include/*.bare lib/include/test/test*.bare
	$(NODE_SHELL) npx bare -s -m lib/include/test/runTests.bare lib/include/test/runTestsMarkdownUp.bare
test-include-markdownup:
	$(NODE_SHELL) npx bare -d -v vUnittestReport true lib/include/test/runTestsMarkdownUp.bare$(if $(TEST), -v vUnittestTest "'$(TEST)'")
test-include-run:
	$(NODE_SHELL) npx bare -d -m lib/include/test/runTests.bare$(if $(TEST), -v vUnittestTest "'$(TEST)'")


doc:
    # Copy statics
	cp -R static/* build/doc/

    # Generate the builtin library documentation
	$(NODE_SHELL) npx bare -m \
		-v 'vFiles' "'$$($(NODE_SHELL) node --input-type=module -e 'console.log(JSON.stringify(process.argv.slice(1)));' lib/library.js)'" \
		-v 'vOutput' "'build/doc/library/library-builtin.json'" \
		-c 'include <baredocCLI.bare>' \
		-c 'return baredocCLIMain()'

    # Generate the include library documentation
	$(NODE_SHELL) npx bare -m \
		-v 'vFiles' "'$$($(NODE_SHELL) node --input-type=module -e 'console.log(JSON.stringify(process.argv.slice(1)));' lib/include/*.bare)'" \
		-v 'vOutput' "'build/doc/library/library-include.json'" \
		-c 'include <baredocCLI.bare>' \
		-c 'return baredocCLIMain()'

    # Generate the single-page library documentation
	cd build/doc/library/ && \
	$(NODE_SHELL) npx bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <baredoc.bare>' \
		-c "baredocMain('library.json')" \
		> barescript-library.md

    # Generate the expression library documentation
	$(NODE_SHELL) node --input-type=module -e "$$DOC_EXPR_JS" build/doc/library/library-builtin.json build/doc/library/expression-builtin.json

    # Generate the single-page expression library documentation
	cd build/doc/library/ && \
	$(NODE_SHELL) npx bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <baredoc.bare>' \
		-c "baredocMain('expression.json')" \
		> barescript-expression-library.md

    # Generate the library model documentation
	$(NODE_SHELL) node --input-type=module -e "$$DOC_LIBRARY_MODEL_JS" build/doc/library/model.json

    # Generate the single-page library model documentation
	cd build/doc/library/ && \
	$(NODE_SHELL) npx bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <schemaDoc.bare>' \
		-c "schemaDocMain('model.json', 'The BareScript Library Models')" \
		> barescript-library-model.md

    # Generate the runtime model documentation
	$(NODE_SHELL) node --input-type=module -e "$$DOC_RUNTIME_MODEL_JS" build/doc/model/model.json

    # Generate the single-page runtime model documentation
	cd build/doc/model/ && \
	$(NODE_SHELL) npx bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <schemaDoc.bare>' \
		-c "schemaDocMain('model.json', 'The BareScript Runtime Model')" \
		> barescript-model.md

    # Publish the AI assistant skill (llms.txt is copied from static/)
	cp SKILL.md build/doc/


# JavaScript to generate the expression library documentation
define DOC_EXPR_JS
import {readFileSync, writeFileSync} from 'node:fs';
import {argv} from 'node:process';
import {expressionFunctionMap} from './lib/library.js';
import {valueJSON} from './lib/value.js';

// Command-line arguments
const [, libraryPath, expressionPath] = argv;

// Read the script library documentation model
const library = JSON.parse(readFileSync(libraryPath, {'encoding': 'utf-8'}));

// Create the expression documentation model
const libraryMap = Object.fromEntries(library.functions.map((func) => [func.name, func]));
const libraryExpr = {'functions': []};
for (const [exprFnName, scriptFnName] of Object.entries(expressionFunctionMap)) {
    libraryExpr.functions.push({...libraryMap[scriptFnName], 'name': exprFnName});
}

// Write the expression documentation model
writeFileSync(expressionPath, valueJSON(libraryExpr));
endef
export DOC_EXPR_JS


# JavaScript to generate the library model documentation
define DOC_LIBRARY_MODEL_JS
import {fetchReadWrite, logStdout} from './lib/optionsNode.js';
import {argv} from 'node:process';
import {executeScriptAsync} from './lib/runtimeAsync.js';
import {barescriptParseScript} from './lib/runtime.js';
import {valueJSON} from './lib/value.js';
import {writeFileSync} from 'node:fs';

// Command-line arguments
const [, typeModelPath] = argv;

// Create the include library type model
const script = barescriptParseScript(`\
include 'lib/include/args.bare'
include 'lib/include/baredoc.bare'
include 'lib/include/data.bare'
include 'lib/include/dataLineChart.bare'
include 'lib/include/dataTable.bare'
include 'lib/include/diff.bare'
include 'lib/include/markdown.bare'
include 'lib/include/markdownElements.bare'
include 'lib/include/markdownHighlight.bare'
include 'lib/include/pager.bare'

includeTypes = {}
objectAssign(includeTypes, argsTypes)
objectAssign(includeTypes, baredocTypes)
objectAssign(includeTypes, dataAggregationTypes)
objectAssign(includeTypes, dataLineChartTypes)
objectAssign(includeTypes, dataTableTypes)
objectAssign(includeTypes, diffTypes)
objectAssign(includeTypes, markdownElementsTypes)
objectAssign(includeTypes, markdownHighlightTypes)
objectAssign(includeTypes, markdownTypes)
objectAssign(includeTypes, pagerTypes)
return includeTypes
`);
const types = await executeScriptAsync(script, {'fetchFn': fetchReadWrite, 'logFn': logStdout});

// Write the library type model
writeFileSync(typeModelPath, valueJSON(types));
endef
export DOC_LIBRARY_MODEL_JS


# JavaScript to generate the runtime model documentation
define DOC_RUNTIME_MODEL_JS
import {argv} from 'node:process';
import {barescriptTypeModel} from './lib/include.js';
import {valueJSON} from './lib/value.js';
import {writeFileSync} from 'node:fs';

// Command-line arguments
const [, typeModelPath] = argv;

// Write the runtime type model
writeFileSync(typeModelPath, valueJSON(barescriptTypeModel()));
endef
export DOC_RUNTIME_MODEL_JS


# Performance test constants
PERF_BARE_PY_DIR := ../bare-script-py
PERF_CSV := build/perf.csv
PERF_CSV_TMP := build/perf-$$PPID.csv
PERF_MERGE := 1
PERF_REPORT := 1
PERF_RUNS := 2


# Run performance tests - write to a temporary CSV ($$PPID is the make process ID) and move it into
# place on success so build/perf.csv is always a complete, valid CSV
.PHONY: perf
perf: build/npm.build
	mkdir -p $(dir $(PERF_CSV_TMP))
	echo "language,test,runs,timeMs" > $(PERF_CSV_TMP)
	set -e; for X in $$(seq 1 $(PERF_RUNS)); do \
		echo "Run $$X of $(PERF_RUNS) - BareScript (JS)"; \
		$(NODE_SHELL) node bin/bare.js perf/test.bare -v vLanguage "'BareScript (JS)'"$(if $(TEST), -v vTest "'$(TEST)'") >> $(PERF_CSV_TMP); \
		echo "Run $$X of $(PERF_RUNS) - JavaScript"; \
		$(NODE_SHELL) node perf/test.js "JavaScript"$(if $(TEST), "$(TEST)") >> $(PERF_CSV_TMP); \
	done
ifneq '$(PERF_MERGE)' ''
ifneq '$(wildcard $(PERF_BARE_PY_DIR))' ''
	$(MAKE) -C $(PERF_BARE_PY_DIR) perf PERF_RUNS=$(PERF_RUNS) TEST=$(TEST) PERF_MERGE= PERF_REPORT=
	tail -n +2 $(PERF_BARE_PY_DIR)/$(PERF_CSV) >> $(PERF_CSV_TMP)
endif
endif
	mv $(PERF_CSV_TMP) $(PERF_CSV)
ifneq '$(PERF_REPORT)' ''
	$(NODE_SHELL) node --input-type=module -e "$$PERF_JS"
endif


# JavsScript to report on performance test data
define PERF_JS
import {readFileSync} from 'node:fs';

// Format a number with trailing zeros trimmed
const numberTrim = (value, digits) => value.toFixed(digits).replace(/\.?0+$$/, '');

// Read the performance test data - compute the best per-run timing per test and language
const testTimings = {};
for (const row of readFileSync('$(PERF_CSV)', 'utf-8').split('\n').slice(1)) {
    if (row !== '') {
        const [language, test, runsText, timeMsText] = row.split(',');
        const timeMs = Number.parseFloat(timeMsText) / Number.parseFloat(runsText);
        const timings = testTimings[test] ?? (testTimings[test] = {});
        if (!(language in timings) || timeMs < timings[language]) {
            timings[language] = timeMs;
        }
    }
}

// Compute the run multiplier - the smallest power of ten that reports every timing at or above one millisecond
let runMultiplier = 1;
const minTiming = Math.min(...Object.values(testTimings).flatMap((timings) => Object.values(timings)));
while (minTiming > 0 && minTiming * runMultiplier < 1) {
    runMultiplier *= 10;
}

// Report the timing multiples for each test
const perRuns = (runMultiplier === 1 ? 'run' : `$${runMultiplier} runs`);
const testEntries = Object.entries(testTimings).sort(([test1], [test2]) => (test1 < test2 ? -1 : 1));
for (const [ixTest, [test, timings]] of testEntries.entries()) {
    if (ixTest !== 0) {
        console.log();
    }
    const bestTiming = Math.min(...Object.values(timings));
    console.log(`$${test}:`);
    for (const [language, timeMs] of Object.entries(timings).sort(([, timeMs1], [, timeMs2]) => timeMs1 - timeMs2)) {
        console.log(`    $${language} - $${(timeMs * runMultiplier).toFixed(1)} milliseconds per $${perRuns} ($${numberTrim(timeMs / bestTiming, 1)}x)`);
    }
}
endef
export PERF_JS
